name: "Configure NPM Scope Action"
description: "Github Action to set scope in a .npmrc file"
inputs:
  accessToken:
    description: "Your access token for the scope"
    required: true
  organization:
    description: "Scope name / organization"
    required: true
  feed:
    description: "Scope feed"
    required: true
  username:
    description: "Your username"
    required: false
  email:
    description: "Your email"
    required: false
    default: "npm requires email to be set but doesn't use the value"
runs:
  using: "node12"
  main: "dist/index.js"
  env:
    NPMRC_PATH: "$HOME/.npmrc"
